"use strict";
const myName=" Abdul Qadeer ";
console.log(myName);
console.log(myName.length);
console.log(myName.toUpperCase());
console.log(myName.toLowerCase());
console.log(myName.trim());
console.log(myName.concat(" Khawaja"));
console.log(myName.endsWith("ja"));
console.log(myName.indexOf("e"));
console.log(myName.substring(0,4));
console.log(myName.slice(0,4));
console.log(myName.replace("Abdul","A"));
console.log(myName.charAt(1));
console.log(myName.split(""));